import nodemailer from "nodemailer";
import { ENV } from "./_core/env";

// Create transporter using environment variables
// For development/testing, you can use Ethereal Email (free SMTP service)
// For production, configure with your email service provider (Gmail, SendGrid, AWS SES, etc.)
const createTransporter = () => {
  // Check if we have email configuration
  const emailConfig = {
    host: process.env.EMAIL_HOST || "smtp.ethereal.email",
    port: parseInt(process.env.EMAIL_PORT || "587"),
    secure: process.env.EMAIL_SECURE === "true", // true for 465, false for other ports
    auth: {
      user: process.env.EMAIL_USER || "",
      pass: process.env.EMAIL_PASSWORD || "",
    },
  };

  // If no credentials provided, log a warning
  if (!emailConfig.auth.user || !emailConfig.auth.pass) {
    console.warn(
      "[Email Service] No email credentials configured. Email sending will be disabled. Set EMAIL_USER and EMAIL_PASSWORD environment variables."
    );
  }

  return nodemailer.createTransport(emailConfig);
};

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType: string;
  }>;
}

export async function sendEmail(options: EmailOptions): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const transporter = createTransporter();

    // Verify transporter connection
    await transporter.verify();

    const mailOptions = {
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER || "noreply@plumbassist.com",
      to: options.to,
      subject: options.subject,
      html: options.html,
      attachments: options.attachments || [],
    };

    const info = await transporter.sendMail(mailOptions);

    return {
      success: true,
      messageId: info.messageId,
    };
  } catch (error) {
    console.error("[Email Service] Error sending email:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to send email",
    };
  }
}

export function generateReportEmailHTML(
  reportType: "inspection" | "quote",
  companyName: string,
  clientName: string,
  referenceNumber: string
): string {
  const reportTitle = reportType === "inspection" ? "Plumbing Inspection Report" : "Plumbing Quote";

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background-color: #1E40AF; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
          .content { background-color: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; border-radius: 0 0 5px 5px; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
          h1 { margin: 0; font-size: 24px; }
          .subtitle { font-size: 14px; opacity: 0.9; margin-top: 5px; }
          .details { margin: 15px 0; }
          .detail-row { margin: 8px 0; }
          .label { font-weight: bold; color: #1E40AF; }
          .cta-button { display: inline-block; background-color: #1E40AF; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; margin-top: 15px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>${reportTitle}</h1>
            <p class="subtitle">Generated by ${companyName}</p>
          </div>
          <div class="content">
            <p>Hello ${clientName},</p>
            
            <p>Your ${reportType === "inspection" ? "plumbing inspection report" : "plumbing quote"} has been prepared and is attached to this email.</p>
            
            <div class="details">
              <div class="detail-row">
                <span class="label">Reference Number:</span> ${referenceNumber}
              </div>
              <div class="detail-row">
                <span class="label">Generated By:</span> ${companyName}
              </div>
              <div class="detail-row">
                <span class="label">Date:</span> ${new Date().toLocaleDateString()}
              </div>
            </div>

            ${
              reportType === "quote"
                ? `
              <p><strong>Quote Validity:</strong> This quote is valid for 14 days from the date above. Please contact us if you have any questions or would like to proceed with the work.</p>
              `
                : `
              <p><strong>Next Steps:</strong> Please review the attached inspection report. We recommend scheduling a follow-up consultation to discuss the findings and recommended actions.</p>
              `
            }

            <p>If you have any questions about this ${reportType === "inspection" ? "report" : "quote"}, please don't hesitate to contact us.</p>

            <p>Best regards,<br><strong>${companyName}</strong></p>
          </div>
          <div class="footer">
            <p>This email was generated by PlumbAssist. Please do not reply to this email.</p>
            <p>&copy; ${new Date().getFullYear()} ${companyName}. All rights reserved.</p>
          </div>
        </div>
      </body>
    </html>
  `;
}
